### ISSUE TITLE
Make config api pure

### ISSUE THREAD

**Issue by Dyumaev** [fit51/reactive-config#3]
Reloadable creation is impure because of using getOrThrow method to obtain initial value. We should have some kind of pure api for guys who doesn't throw exceptions in their code. What if we add some methods which don't throw exceptions and return result wrapped in F[_] or maybe create another config implementation which is pure?

**Comment by fit51** [comment]
Truly speaking, creation of Reloadable is not the only place we have impure API.
Look at Reloadable.get that returns T. Every time you call it, you my get a new, updated value. So .get is not a pure function by it's idea.

The library api was designed for an easy typesafe config replacement. 
Typesafe config api is not pure, so you can initialize application services eager and without effect composition. 
And the common pattern is, when on start-up application eagerly and synchronously loads configuration. If it fails, app should not start.

**Comment by fit51** [comment]
We have 2 options:
- Pure Api and effects when creating configuration and using it. (Everything is wrapped in F[_])
- Impure Api and ability to replace constants with values from config without much refactoring.(similar to typesafe config)

**Comment by Dyumaev** [comment]
Api compatible with typesafe config can be easily created from the pure one. I'll add one more type parameter I[_] which will require only MonadError. So one can use Try if he needs eager evaluation. On the other hand someone can use something more functional and get pure Api.

All impure calculations take place in safeReload method which is already in F context. The only thing left is referential transparency. We have several options:
- change get signature to `def get: F[B]` 
- create one more get method which delays execution `def get: F[B] = F.delay(get)`
- leave get without changes

I think that third option is better because user can take care of purity on his own: one can do something like `def pureGet: Task[B] = reloadable.observable.lastL` or `def pureGet: F[B] = F.delay(reloadable.get)` or maybe just use impure `def get: B`

**Comment by fit51** [comment]
> Api compatible with typesafe config can be easily created from the pure one. I'll add one more type parameter I[_] which will require only MonadError. So one can use Try if he needs eager evaluation. On the other hand someone can use something more functional and get pure Api.

I don't think additional typeParameter I[_] is required. There is a pure general function get, that returns a Try[T]. Other methods like getOption, getOrThrow are just helpers. We can get rid of getOrThrow if it is the only problem in typesafe-like api for you.

**Comment by fit51** [comment]
While writing an example https://github.com/fit51/reactive-config/blob/master/examples/src/main/scala/com/github/fit51/reactiveconfig/examples/EtcdConfigApplication.scala I realized, we should focus on tagless final, and make creation of ReactiveConfig, Reloadables effectfull 'F[_]' .
Thow, we could eliminate TaskLike typeclass and monix Scheduler and require `them only at the end of the world`.

**Comment by fit51** [comment]
#8
