### ISSUE TITLE
Abstract over monix

### ISSUE THREAD

**Issue by Dyumaev** [fit51/reactive-config#4]
There are many reactive solutions people might want to use. We must not impose them to use monix. We can make something abstract inside and ship monix implementation as module. So people can make their own implementation with rx, fs2 or whatever

**Comment by fit51** [comment]
I don't agree that it's a good idea to abstract monix Observable. This whole library is about implementing Reactive Config in monix. The only reactive abstraction that exists today is Reactive Streams, and monix Observable-s actually implements it.

**Comment by fit51** [comment]
The other thing, we need to discuss is how we abstract over F[ _ ] effect in our library interfaces.
There is problem, that we use monix Оbservable as inner implementation of Reloadable and it leads us to TaskLike typeclass requirement.

**Comment by fit51** [comment]
And by the way, abstracting over monix is the last thing we should. Let's start with implementing robust, solid and tested solution on monix)

**Comment by Dyumaev** [comment]
Agree. I used TaskLike to support both Futures and Effects. It can be easily replaced with Effect typeclass as we decided not to support Futures. 
We still can abstract over Monix later simply using ReactiveStreams interfaces.
